name: maquisistema_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  cached_network_image: ^3.3.1
  page_transition: ^2.1.0
  flutter_svg: ^2.0.10+1
  flutter_tabler_icons: ^1.25.0
  intl: ^0.19.0
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.7
  internet_connection_checker_plus: ^2.2.0
  timezone: ^0.9.2

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  image: assets/images/maquisistema-splash.png
  image_dark: assets/images/maquisistema-splash.png

  android_12:
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#FFFFFF"
    image: assets/images/maquisistema-splash.png
    image_dark: assets/images/maquisistema-splash.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Bold.ttf
        - asset: assets/fonts/Mulish-Medium.ttf
        - asset: assets/fonts/Mulish-Regular.ttf
        - asset: assets/fonts/Mulish-Light.ttf
